version: "2"
services:
  nginx:
    image: nginx:1.15-alpine
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 9080:9080
#      - 9443:9443
